### ISSUE TITLE
Ceph vagrant errors

### ISSUE THREAD

**Issue by kacole2** [thecodeteam/vagrant#31]
@codenrhoden I'm getting this error on `vagrant up`

```
==> ceph-admin: Running provisioner: shell...
    ceph-admin: Running: /var/folders/62/__8dkrv505g9v_psmpqq38hw0000gn/T/vagrant-shell20161214-37934-1c23z9j.sh
==> ceph-admin: + NUM_NODES=2
==> ceph-admin: + '[' -e /etc/ceph/ceph.conf ']'
==> ceph-admin: + tee /home/vagrant/.ssh/config
==> ceph-admin: Host *
==> ceph-admin:    StrictHostKeyChecking no
==> ceph-admin:    UserKnownHostsFile=/dev/null
==> ceph-admin: + chmod 0600 /home/vagrant/.ssh/config
==> ceph-admin: + '[' 2 -ge 3 ']'
==> ceph-admin: + ceph-deploy new ceph-server-1
==> ceph-admin: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
==> ceph-admin: [ceph_deploy.cli][INFO  ] Invoked (1.5.36): /usr/bin/ceph-deploy new ceph-server-1
==> ceph-admin: [ceph_deploy.cli][INFO  ] ceph-deploy options:
==> ceph-admin: [ceph_deploy.cli][INFO  ]  username                      : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  func                          : <function new at 0x7f0a953c5398>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  verbose                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  overwrite_conf                : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  quiet                         : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x7f0a94b359e0>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster                       : ceph
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ssh_copykey                   : True
==> ceph-admin: [ceph_deploy.cli][INFO  ]  mon                           : ['ceph-server-1']
==> ceph-admin: [ceph_deploy.cli][INFO  ]  public_network                : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ceph_conf                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster_network               : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  default_release               : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  fsid                          : None
==> ceph-admin: [ceph_deploy.new][DEBUG ] Creating new cluster named ceph
==> ceph-admin: [ceph_deploy.new][INFO  ] making sure passwordless SSH succeeds
==> ceph-admin: [ceph-server-1][DEBUG ] connected to host: ceph-admin
==> ceph-admin: [ceph-server-1][INFO  ] Running command: ssh -CT -o BatchMode=yes ceph-server-1
==> ceph-admin: [ceph_deploy.new][WARNING] could not connect via SSH
==> ceph-admin: [ceph_deploy.new][INFO  ] creating a passwordless id_rsa.pub key file
==> ceph-admin: [ceph_deploy.new][DEBUG ] connected to host: ceph-admin
==> ceph-admin: [ceph_deploy.new][INFO  ] Running command: ssh-keygen -t rsa -N  -f /home/vagrant/.ssh/id_rsa
==> ceph-admin: [ceph_deploy.new][DEBUG ] Generating public/private rsa key pair.
==> ceph-admin: [ceph_deploy.new][DEBUG ] Your identification has been saved in /home/vagrant/.ssh/id_rsa.
==> ceph-admin: [ceph_deploy.new][DEBUG ] Your public key has been saved in /home/vagrant/.ssh/id_rsa.pub.
==> ceph-admin: [ceph_deploy.new][DEBUG ] The key fingerprint is:
==> ceph-admin: [ceph_deploy.new][DEBUG ] 20:70:a5:a4:68:47:24:26:f8:c5:83:6f:45:2c:1d:c1 vagrant@ceph-admin
==> ceph-admin: [ceph_deploy.new][DEBUG ] The key's randomart image is:
==> ceph-admin: [ceph_deploy.new][DEBUG ] +--[ RSA 2048]----+
==> ceph-admin: [ceph_deploy.new][DEBUG ] |ooo=o*=o         |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |+.+==.E          |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |.o.+o+.          |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |. o o. .         |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |   .    S        |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |                 |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |                 |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |                 |
==> ceph-admin: [ceph_deploy.new][DEBUG ] |                 |
==> ceph-admin: [ceph_deploy.new][DEBUG ] +-----------------+
==> ceph-admin: [ceph_deploy.new][INFO  ] will connect again with password prompt
==> ceph-admin: Warning: Permanently added 'ceph-server-1,172.21.13.11' (ECDSA) to the list of known hosts.
==> ceph-admin: Permission denied, please try again.
==> ceph-admin: Permission denied, please try again.
==> ceph-admin: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
==> ceph-admin: [ceph_deploy][ERROR ] RuntimeError: connecting to host: ceph-server-1 resulted in errors: HostNotFound ceph-server-1
==> ceph-admin: + '[' 2 == 1 ']'
==> ceph-admin: + '[' 2 == 2 ']'
==> ceph-admin: + tee -a ceph.conf
==> ceph-admin: osd pool default size = 2
==> ceph-admin: osd pool default min size = 1
==> ceph-admin: + ceph-deploy mon create-initial
==> ceph-admin: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
==> ceph-admin: [ceph_deploy.cli][INFO  ] Invoked (1.5.36): /usr/bin/ceph-deploy mon create-initial
==> ceph-admin: [ceph_deploy.cli][INFO  ] ceph-deploy options:
==> ceph-admin: [ceph_deploy.cli][INFO  ]  username                      : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  verbose                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  overwrite_conf                : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  subcommand                    : create-initial
==> ceph-admin: [ceph_deploy.cli][INFO  ]  quiet                         : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x7fb9fcd54290>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster                       : ceph
==> ceph-admin: [ceph_deploy.cli][INFO  ]  func                          : <function mon at 0x7fb9fcd49320>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ceph_conf                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  default_release               : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  keyrings                      : None
==> ceph-admin: [ceph_deploy][ERROR ] Traceback (most recent call last):
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/util/decorators.py", line 69, in newfunc
==> ceph-admin: [ceph_deploy][ERROR ]     return f(*a, **kw)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/cli.py", line 170, in _main
==> ceph-admin: [ceph_deploy][ERROR ]     return args.func(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/mon.py", line 470, in mon
==> ceph-admin: [ceph_deploy][ERROR ]     mon_create_initial(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/mon.py", line 414, in mon_create_initial
==> ceph-admin: [ceph_deploy][ERROR ]     mon_initial_members = get_mon_initial_members(args, error_on_empty=True)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/mon.py", line 560, in get_mon_initial_members
==> ceph-admin: [ceph_deploy][ERROR ]     cfg = conf.ceph.load(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 71, in load
==> ceph-admin: [ceph_deploy][ERROR ]     return parse(f)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 52, in parse
==> ceph-admin: [ceph_deploy][ERROR ]     cfg.readfp(ifp)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
==> ceph-admin: [ceph_deploy][ERROR ]     self._read(fp, filename)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
==> ceph-admin: [ceph_deploy][ERROR ]     raise MissingSectionHeaderError(fpname, lineno, line)
==> ceph-admin: [ceph_deploy][ERROR ] MissingSectionHeaderError: File contains no section headers.
==> ceph-admin: [ceph_deploy][ERROR ] file: <???>, line: 1
==> ceph-admin: [ceph_deploy][ERROR ] 'osd pool default size = 2\n'
==> ceph-admin: [ceph_deploy][ERROR ]
==> ceph-admin: ++ seq 1 2
==> ceph-admin: + for x in '$(seq 1 $NUM_NODES)'
==> ceph-admin: + ceph-deploy osd create --zap-disk ceph-server-1:/dev/sdb
==> ceph-admin: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
==> ceph-admin: [ceph_deploy.cli][INFO  ] Invoked (1.5.36): /usr/bin/ceph-deploy osd create --zap-disk ceph-server-1:/dev/sdb
==> ceph-admin: [ceph_deploy.cli][INFO  ] ceph-deploy options:
==> ceph-admin: [ceph_deploy.cli][INFO  ]  username                      : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  disk                          : [('ceph-server-1', '/dev/sdb', None)]
==> ceph-admin: [ceph_deploy.cli][INFO  ]  dmcrypt                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  verbose                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  bluestore                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  overwrite_conf                : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  subcommand                    : create
==> ceph-admin: [ceph_deploy.cli][INFO  ]  dmcrypt_key_dir               : /etc/ceph/dmcrypt-keys
==> ceph-admin: [ceph_deploy.cli][INFO  ]  quiet                         : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0xe62200>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster                       : ceph
==> ceph-admin: [ceph_deploy.cli][INFO  ]  fs_type                       : xfs
==> ceph-admin: [ceph_deploy.cli][INFO  ]  func                          : <function osd at 0xe52b90>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ceph_conf                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  default_release               : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  zap_disk                      : True
==> ceph-admin: [ceph_deploy][ERROR ] Traceback (most recent call last):
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/util/decorators.py", line 69, in newfunc
==> ceph-admin: [ceph_deploy][ERROR ]     return f(*a, **kw)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/cli.py", line 170, in _main
==> ceph-admin: [ceph_deploy][ERROR ]     return args.func(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/osd.py", line 580, in osd
==> ceph-admin: [ceph_deploy][ERROR ]     cfg = conf.ceph.load(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 71, in load
==> ceph-admin: [ceph_deploy][ERROR ]     return parse(f)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 52, in parse
==> ceph-admin: [ceph_deploy][ERROR ]     cfg.readfp(ifp)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
==> ceph-admin: [ceph_deploy][ERROR ]     self._read(fp, filename)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
==> ceph-admin: [ceph_deploy][ERROR ]     raise MissingSectionHeaderError(fpname, lineno, line)
==> ceph-admin: [ceph_deploy][ERROR ] MissingSectionHeaderError: File contains no section headers.
==> ceph-admin: [ceph_deploy][ERROR ] file: <???>, line: 1
==> ceph-admin: [ceph_deploy][ERROR ] 'osd pool default size = 2\n'
==> ceph-admin: [ceph_deploy][ERROR ]
==> ceph-admin: + for x in '$(seq 1 $NUM_NODES)'
==> ceph-admin: + ceph-deploy osd create --zap-disk ceph-server-2:/dev/sdb
==> ceph-admin: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
==> ceph-admin: [ceph_deploy.cli][INFO  ] Invoked (1.5.36): /usr/bin/ceph-deploy osd create --zap-disk ceph-server-2:/dev/sdb
==> ceph-admin: [ceph_deploy.cli][INFO  ] ceph-deploy options:
==> ceph-admin: [ceph_deploy.cli][INFO  ]  username                      : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  disk                          : [('ceph-server-2', '/dev/sdb', None)]
==> ceph-admin: [ceph_deploy.cli][INFO  ]  dmcrypt                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  verbose                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  bluestore                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  overwrite_conf                : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  subcommand                    : create
==> ceph-admin: [ceph_deploy.cli][INFO  ]  dmcrypt_key_dir               : /etc/ceph/dmcrypt-keys
==> ceph-admin: [ceph_deploy.cli][INFO  ]  quiet                         : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x10da200>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster                       : ceph
==> ceph-admin: [ceph_deploy.cli][INFO  ]  fs_type                       : xfs
==> ceph-admin: [ceph_deploy.cli][INFO  ]  func                          : <function osd at 0x10cab90>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ceph_conf                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  default_release               : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  zap_disk                      : True
==> ceph-admin: [ceph_deploy][ERROR ] Traceback (most recent call last):
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/util/decorators.py", line 69, in newfunc
==> ceph-admin: [ceph_deploy][ERROR ]     return f(*a, **kw)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/cli.py", line 170, in _main
==> ceph-admin: [ceph_deploy][ERROR ]     return args.func(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/osd.py", line 580, in osd
==> ceph-admin: [ceph_deploy][ERROR ]     cfg = conf.ceph.load(args)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 71, in load
==> ceph-admin: [ceph_deploy][ERROR ]     return parse(f)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib/python2.7/site-packages/ceph_deploy/conf/ceph.py", line 52, in parse
==> ceph-admin: [ceph_deploy][ERROR ]     cfg.readfp(ifp)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
==> ceph-admin: [ceph_deploy][ERROR ]     self._read(fp, filename)
==> ceph-admin: [ceph_deploy][ERROR ]   File "/usr/lib64/python2.7/ConfigParser.py", line 512, in _read
==> ceph-admin: [ceph_deploy][ERROR ]     raise MissingSectionHeaderError(fpname, lineno, line)
==> ceph-admin: [ceph_deploy][ERROR ] MissingSectionHeaderError: File contains no section headers.
==> ceph-admin: [ceph_deploy][ERROR ] file: <???>, line: 1
==> ceph-admin: [ceph_deploy][ERROR ] 'osd pool default size = 2\n'
==> ceph-admin: [ceph_deploy][ERROR ]
==> ceph-admin: + ceph-deploy admin localhost
==> ceph-admin: [ceph_deploy.conf][DEBUG ] found configuration file at: /home/vagrant/.cephdeploy.conf
==> ceph-admin: [ceph_deploy.cli][INFO  ] Invoked (1.5.36): /usr/bin/ceph-deploy admin localhost
==> ceph-admin: [ceph_deploy.cli][INFO  ] ceph-deploy options:
==> ceph-admin: [ceph_deploy.cli][INFO  ]  username                      : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  verbose                       : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  overwrite_conf                : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  quiet                         : False
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cd_conf                       : <ceph_deploy.conf.cephdeploy.Conf instance at 0x17fcf80>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  cluster                       : ceph
==> ceph-admin: [ceph_deploy.cli][INFO  ]  client                        : ['localhost']
==> ceph-admin: [ceph_deploy.cli][INFO  ]  func                          : <function admin at 0x7f81e26d4140>
==> ceph-admin: [ceph_deploy.cli][INFO  ]  ceph_conf                     : None
==> ceph-admin: [ceph_deploy.cli][INFO  ]  default_release               : False
==> ceph-admin: [ceph_deploy][ERROR ] RuntimeError: ceph.client.admin.keyring not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by codenrhoden** [comment]
@kacole2 thankfully this has a documentation fix!  I knew I needed to add it, then forgot.  :/

While the vagrant box image has the default vagrant SSH insecure key in place, and SSH key forward is enabled, you are still required to actually add the vagrant insecure key to your SSH agent.  This is most easily done with `ssh-add ~/.vagrant.d/insecure_private_key`. You can always see what keys you have loaded in your SSH agent with `ssh-add -l`.

Most people don't try to SSH from vagrant VM to vagrant VM, but that's what I am doing here. The `ceph-deploy` tool operates over SSH, and that's the error you are seeing.

Sorry for the omission!

**Comment by kacole2** [comment]
right on. will try it out again tonight. nice work so far

Kendrick Coleman

kendrickcoleman.com
@KendrickColeman
github.com/kacole2

**Comment by pdildako** [comment]
> @kacole2 thankfully this has a documentation fix! I knew I needed to add it, then forgot. :/
> 
> While the vagrant box image has the default vagrant SSH insecure key in place, and SSH key forward is enabled, you are still required to actually add the vagrant insecure key to your SSH agent. This is most easily done with `ssh-add ~/.vagrant.d/insecure_private_key`. You can always see what keys you have loaded in your SSH agent with `ssh-add -l`.
> 
> Most people don't try to SSH from vagrant VM to vagrant VM, but that's what I am doing here. The `ceph-deploy` tool operates over SSH, and that's the error you are seeing.
> 
> Sorry for the omission!

where is document for this fix
